### ISSUE TITLE
codeclimate analyze --dev fails

### ISSUE THREAD

**Issue by marekdedic** [antiagainst/codeclimate-cppcheck#8]
I installed the engine locally (by running `docker build -t codeclimate/codeclimate-cppcheck .`) and tried running it by `codeclimate analyze --dev`. What I got is:
```
Starting analysis
Running cppcheck: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine cppcheck:stable failed with status 1 and stderr 
[cppcheck] config: {} {'enabled': True, 'include_paths': ['.codeclimate.yml', '.idea/', 'images.qrc', 'src/', 'LICENSE', 'CppCheckResults.txt', 'cppcheck.sh', 'non-code data/', 'include/', 'resources/', 'CMakeLists.txt', '.gitignore', 'cmake-build-debug/', 'README.md']}
Traceback (most recent call last):
  File "/usr/src/app/codeclimate-cppcheck.py", line 173, in <module>
    parse_cppcheck_results(run_cppcheck())
  File "/usr/src/app/codeclimate-cppcheck.py", line 87, in run_cppcheck
    p = subprocess.Popen(get_cppcheck_command(),
  File "/usr/src/app/codeclimate-cppcheck.py", line 76, in get_cppcheck_command
    args, filelist = get_config_and_filelist()
  File "/usr/src/app/codeclimate-cppcheck.py", line 44, in get_config_and_filelist
    files = get_src_files(include_paths)
  File "/usr/src/app/codeclimate-cppcheck.py", line 23, in get_src_files
    os.chdir(path)
NotADirectoryError: [Errno 20] Not a directory: '.codeclimate.yml'
```

My `.codeclimate.yml` contains:
```yaml
engines:
  cppcheck:
    enabled: true
ratings:
  paths: []
exclude_paths: []
```

**Comment by marekdedic** [comment]
Can confirm, the issue is fixed for me. Thank you.

**Comment by antiagainst** [comment]
Thanks @GenaBitu! I must say sorry that it took me such a long time to attend to this issue. At the current moment, my focus is basically shifted away from this project. You are very welcome to contribute and make it useful to you. :)
